#Euler-Maruyama method for p-dim special SDE
#Y(t) = b^T*X(t)
#dX(t) = [A*X(t)+C*Z(t)]dt + e_p*dW_t, X(S) = X0, t in [S,T]

#'as' and 'X0' must have dimension 'p'
#'bs' must have dimension 'q'
#'cs' and 'Z' must have the same dimension
euler_maruyama_for_new_sde <- function(p, q, as, bs, cs, Z, X0, S=0, T=1, N=1000) {
  
  #Assert that input values fit the given model and its restrictions
  if(q>=p) stop ("'p' must be bigger than 'q'.")
  if(length(as)!=p) stop("'as' must have dimension 'p'.")
  if(length(bs)!=q) stop("'bs' must have dimension 'q'.")
  if(length(cs)!=length(Z(0))) stop("'cs' and 'Z' must have the same dimension.")
  if(length(X0)!=p) stop("'X0' must have dimension 'p'.")
  
  #Define length of time discretization subinterval
  tau <- (T-S)/N
  
  #Define time vector
  times <- seq(from=S, to=T, length.out=N+1)
  
  #Build vector b for state space representation
  b <- c(bs, 1, rep(0,p-(q+1)))
  
  #Define empty matrix X to store the results
  X <- matrix(data=NA, nrow=p, ncol=N+1)
  
  #Set initial value 
  X[,1] <- X0
  
  #Approximate the SDE - Euler-Maruyama scheme
  for (i in 2:(N+1)) {
    
    for (j in 1:p) {
      
      if(j!=p) 
      {
        X[j,i] <- X[j,i-1] + (tau * X[j+1,i-1])
      }
      else 
      {
        X[j,i] <- X[j,i-1] + (tau * (sum(rev(as)*X[,i-1]) + sum(rev(cs)*Z(times[i-1])))) + sqrt(tau)*rnorm(1)
      }
      
    }
    
  }
  
  #Apply vector b for state space representation
  Y = colSums(b*X)
  
  #Save results to list 
  result_list <- list(times, Y, X)
  
  #Name columns of the list
  names(result_list) <- c("time", "observed_process", "unobserved_processes")
  
  #Return (invisible) list
  return(invisible(result_list))
}

#
#
#

#Example
Z <- function(t) {return(c(t^2,t^2,t^2))}

sim <- euler_maruyama_for_new_sde(p=3, q=2, as=c(-1,-2,-3), bs=c(1,2), cs=c(-3,-2,-1), Z=Z, X0=rep(0,3))

#
#
#

library(ggplot2)

#This method plots the trajectories generated by euler_maruyama_for_new_sde
plot_new_sde <- function(sim)
{
  #Get p and N from data input
  p <- dim(sim$unobserved_processes)[1]
  N <- dim(sim$unobserved_processes)[2]
  
  #Convert input to dataframe
  df <- data.frame(value = c(t(sim$unobserved_processes)),
                   label = rep(paste("X", 1:p, sep=""), each = N),
                   time = rep(sim$time, p))
  
  #Add observed process Y to dataframe
  df <- rbind(df, data.frame(value = sim$observed_process, label = rep("Y", N), time = sim$time))
  
  #Save labels as factor  
  df$label <- factor(df$label, levels = c("Y", paste("X", 1:p, sep="")))
  
  #Call ggplot
  ggplot(df, aes(x = time, y = value)) +
    geom_line() +
    labs(y = "") +
    scale_y_continuous(expand = c(0.1, 0.1)) +
    facet_grid(label ~ ., switch = "y", scales = "free_y") +
    theme_classic() +
    theme(strip.background = element_blank(),
          strip.placement  = "outside",
          panel.spacing    = unit(0, "lines"),
          panel.border = element_rect(color = "black", fill = NA))
}

#Example
plot_new_sde(sim)




